[package]
name = "yazelix-zellij-pane-orchestrator"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[[bin]]
name = "yazelix_zellij_pane_orchestrator"
path = "src/main.rs"
bench = false

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
zellij-tile = { git = "https://github.com/zellij-org/zellij", rev = "81f56e1aed4e17b822af5cb382a8f524e35f3eae" }
